In [17]:
import requests
import json
import pandas as pd
from datetime import date,time,datetime,timedelta
from openpyxl import load_workbook
import itertools
import math

In [2]:
auth_token_hiya="fc3ed86b62485a2b9a6a680477ea7e60"
auth_token_rawble="e8253e7e6017303a54f57ce28b9d209a"
organization_id_hiya="654806043"
organization_id_rawble = "667580392"
base_url = "https://books.zoho.com/api/v3"
end_points = {'invoices':'/invoices','crm':'/crm','contacts':'/contacts','account':'/account','bills':'/bills'}

In [3]:
page_number = 1
parameters={'authtoken':auth_token_hiya,'organization_id':organization_id_hiya}
parameters['page'] = page_number
response = requests.get(base_url+end_points['invoices'],params=parameters)
#while(response.json()['page_context']['has_more_page'] == True):
df_list = []
for i in itertools.count():
    parameters['page'] = page_number + i
    response = requests.get(base_url + end_points['bills'],params = parameters)
    df_temp = pd.DataFrame(response.json()['bills'])
    df_list.append(df_temp)
    print(parameters)
    if(response.json()['page_context']['has_more_page'] != True):
        break
print(len(df_list))

{'authtoken': 'fc3ed86b62485a2b9a6a680477ea7e60', 'organization_id': '654806043', 'page': 1}
{'authtoken': 'fc3ed86b62485a2b9a6a680477ea7e60', 'organization_id': '654806043', 'page': 2}
{'authtoken': 'fc3ed86b62485a2b9a6a680477ea7e60', 'organization_id': '654806043', 'page': 3}
{'authtoken': 'fc3ed86b62485a2b9a6a680477ea7e60', 'organization_id': '654806043', 'page': 4}
4

In [4]:
df_bill_sheet = pd.concat(df_list,axis=0,sort=False)

In [5]:
print(list(df_bill_sheet))

['attachment_name', 'balance', 'bill_id', 'bill_number', 'cf_bill', 'client_viewed_time', 'created_time', 'currency_code', 'currency_id', 'current_sub_status', 'current_sub_status_id', 'date', 'due_date', 'due_days', 'entity_type', 'exchange_rate', 'has_attachment', 'is_tds_applied', 'is_viewed_by_client', 'last_modified_time', 'price_precision', 'reference_number', 'status', 'tds_total', 'total', 'vendor_id', 'vendor_name']

In [11]:
print(df_bill_sheet[['status','created_time','last_modified_time','date','due_date']])

              status              created_time        last_modified_time  \
0               paid  2018-06-26T15:12:01+0530  2018-06-26T15:13:39+0530
1               paid  2018-06-26T15:08:08+0530  2018-06-26T15:13:39+0530
2   pending_approval  2018-06-26T15:02:31+0530  2018-06-26T15:02:32+0530
3   pending_approval  2018-06-26T14:58:24+0530  2018-06-26T14:58:25+0530
4              draft  2018-06-25T06:43:00+0530  2018-06-25T06:43:00+0530
5            overdue  2018-06-23T10:59:03+0530  2018-06-23T11:40:36+0530
6               paid  2018-06-23T10:51:35+0530  2018-06-23T10:54:00+0530
7               paid  2018-06-23T10:49:08+0530  2018-06-23T10:54:00+0530
8               paid  2018-06-22T16:33:23+0530  2018-06-23T11:40:36+0530
9            overdue  2018-06-22T14:34:06+0530  2018-06-22T14:39:26+0530
10              paid  2018-06-21T15:29:03+0530  2018-06-21T15:31:49+0530
11           overdue  2018-06-20T14:28:30+0530  2018-06-21T14:44:06+0530
12           overdue  2018-06-20T14:24:00+0530  2018-06-21T14:44:06+0530
13              paid  2018-06-20T14:21:13+0530  2018-06-21T14:44:06+0530
14    partially_paid  2018-06-20T11:08:01+0530  2018-06-20T11:09:11+0530
15              open  2018-06-19T14:45:08+0530  2018-06-22T14:33:51+0530
16    partially_paid  2018-06-19T14:26:40+0530  2018-06-23T12:00:07+0530
17           overdue  2018-06-19T11:17:06+0530  2018-06-22T17:11:34+0530
18              open  2018-06-18T16:02:32+0530  2018-06-22T14:34:26+0530
19           overdue  2018-06-18T15:55:17+0530  2018-06-25T17:47:56+0530
20           overdue  2018-06-18T15:42:43+0530  2018-06-25T17:47:35+0530
21              paid  2018-06-18T15:34:24+0530  2018-06-26T15:17:06+0530
22              paid  2018-06-18T15:25:44+0530  2018-06-26T15:17:06+0530
23           overdue  2018-06-18T15:16:32+0530  2018-06-22T14:30:28+0530
24           overdue  2018-06-18T14:35:12+0530  2018-06-22T14:30:38+0530
25              open  2018-06-18T14:18:37+0530  2018-06-22T14:31:21+0530
26              open  2018-06-18T13:52:54+0530  2018-06-22T14:30:57+0530
27           overdue  2018-06-18T13:09:50+0530  2018-06-18T13:14:41+0530
28              paid  2018-06-18T13:07:05+0530  2018-06-18T13:23:47+0530
29              paid  2018-06-18T13:06:27+0530  2018-06-18T13:23:06+0530
..               ...                       ...                       ...
18              paid  2017-11-10T11:05:43+0530  2017-11-10T11:06:05+0530
19              paid  2017-11-09T16:06:45+0530  2017-11-09T16:10:16+0530
20           overdue  2017-11-06T13:24:38+0530  2017-11-06T13:24:38+0530
21              paid  2017-11-03T10:55:04+0530  2018-04-19T14:34:16+0530
22           overdue  2017-11-03T10:33:07+0530  2018-06-20T11:13:55+0530
23           overdue  2017-11-02T18:29:56+0530  2017-11-02T18:29:56+0530
24           overdue  2017-11-02T17:22:29+0530  2018-03-10T15:35:32+0530
25           overdue  2017-11-02T17:21:14+0530  2018-05-08T15:18:54+0530
26           overdue  2017-11-02T16:52:43+0530  2017-11-02T16:52:43+0530
27           overdue  2017-11-02T16:51:11+0530  2017-11-02T16:51:11+0530
28           overdue  2017-11-02T16:49:26+0530  2017-11-02T16:49:26+0530
29           overdue  2017-11-02T16:43:51+0530  2017-11-02T16:44:29+0530
30           overdue  2017-11-02T16:38:47+0530  2018-06-20T11:12:43+0530
31           overdue  2017-11-02T16:23:29+0530  2017-11-02T16:46:58+0530
32           overdue  2017-11-02T13:16:54+0530  2017-11-02T13:16:54+0530
33              paid  2017-11-02T12:59:51+0530  2018-05-08T15:18:54+0530
34           overdue  2017-10-31T17:18:06+0530  2018-06-21T12:53:34+0530
35           overdue  2017-10-31T15:21:08+0530  2017-10-31T15:21:08+0530
36              paid  2017-10-31T14:39:40+0530  2018-06-20T11:13:55+0530
37              paid  2017-10-31T13:24:36+0530  2018-05-08T15:17:46+0530
38              paid  2017-10-31T13:20:14+0530  2018-05-08T15:18:54+0530
39              paid  2017-10-31T13:14:06+0530  2018-05-08T15:18:54+0530
40              paid  2017-10-31T13:05:38+0530  2018-05-08T15:15:04+0530
41              paid  2017-10-31T13:00:01+0530  2018-05-08T15:15:04+0530
42           overdue  2017-10-31T12:48:00+0530  2017-10-31T12:48:00+0530
43           overdue  2017-10-31T12:29:04+0530  2017-10-31T12:29:04+0530
44           overdue  2017-10-31T12:24:51+0530  2017-10-31T12:24:51+0530
45           overdue  2017-10-31T11:23:18+0530  2018-06-20T11:10:12+0530
46              paid  2017-10-31T11:08:40+0530  2018-06-22T15:02:21+0530
47              paid  2017-10-27T16:31:09+0530  2017-10-27T16:33:48+0530

          date    due_date
0   2018-06-01  2018-06-08
1   2018-06-01  2018-06-08
2   2018-06-19  2018-07-19
3   2018-06-19  2018-07-19
4   2018-06-25  2018-07-25
5   2018-05-01  2018-05-31
6   2018-05-31  2018-06-07
7   2018-05-31  2018-06-07
8   2018-04-01  2018-05-01
9   2018-04-12  2018-04-19
10  2018-04-01  2018-04-16
11  2018-06-02  2018-06-17
12  2018-06-02  2018-06-17
13  2018-06-02  2018-06-17
14  2018-06-08  2018-07-08
15  2018-06-17  2018-09-17
16  2018-05-30  2018-06-29
17  2018-05-31  2018-06-20
18  2018-06-12  2018-07-12
19  2018-06-12  2018-06-18
20  2018-06-15  2018-06-18
21  2018-06-12  2018-06-12
22  2018-06-12  2018-06-12
23  2018-05-28  2018-05-28
24  2018-05-29  2018-06-18
25  2018-06-08  2018-09-08
26  2018-05-01  2018-08-01
27  2018-04-30  2018-05-15
28  2018-05-31  2018-06-15
29  2018-05-31  2018-06-15
..         ...         ...
18  2017-11-07  2017-11-07
19  2017-11-08  2017-11-08
20  2017-11-04  2017-12-03
21  2017-11-10  2017-11-10
22  2017-10-27  2018-01-26
23  2017-11-26  2018-01-25
24  2017-10-31  2018-01-31
25  2017-10-31  2018-01-31
26  2017-10-13  2017-11-12
27  2017-10-06  2017-11-06
28  2017-10-06  2017-11-06
29  2017-10-23  2017-12-22
30  2017-10-12  2017-11-12
31  2017-10-25  2017-11-25
32  2017-10-31  2017-11-30
33  2017-10-26  2018-01-25
34  2017-10-12  2017-12-11
35  2017-10-30  2018-01-29
36  2017-10-11  2018-01-10
37  2017-10-23  2018-01-22
38  2017-10-23  2018-01-22
39  2017-10-26  2018-01-25
40  2017-10-10  2018-01-09
41  2017-10-06  2017-12-05
42  2017-10-16  2018-01-15
43  2017-10-10  2018-01-09
44  2017-10-06  2018-01-05
45  2017-10-05  2018-01-04
46  2017-10-30  2018-01-29
47  2017-10-24  2017-10-27

[648 rows x 5 columns]

In [18]:
df_new = pd.DataFrame()
for i in range(len(df_bill_sheet)):
    #df_temp = pd.DataFrame()
    if(df_bill_sheet.iloc[i]['status']=='paid'):
        vendor_name = df_bill_sheet.iloc[i]['vendor_name']
        difference_date  = (datetime.strptime(str(df_bill_sheet.iloc[i]['last_modified_time']).split("T")[0],'%Y-%m-%d').date()-datetime.strptime(df_bill_sheet.iloc[i]['due_date'],'%Y-%m-%d').date()).days
        #print(df_invoice_sheet.iloc[i]['customer_name'],df_invoice_sheet.iloc[i]['date'],df_invoice_sheet.iloc[i]['due_date'],df_invoice_sheet.iloc[i]['status'])
        #print((datetime.strptime(df_invoice_sheet.iloc[i]['due_date'],'%Y-%m-%d').date()-datetime.strptime#(df_invoice_sheet.iloc[i]['date'],'%Y-%m-%d').date()).days)
        amount = df_bill_sheet.iloc[i]['total']
        df_new = df_new.append({
            'vendor_name':vendor_name,'difference_days_avg':difference_date,'amount':amount,
        },ignore_index=True)
    #df_new = df_temp
g = df_new.groupby('vendor_name')
df_new["weighted_avg"] = (df_new.difference_days_avg / g.amount.transform("sum")) * df_new.amount
df_new_2 = pd.DataFrame(df_new.groupby('vendor_name').agg({'weighted_avg':'sum','difference_days_avg':'mean'}))

In [19]:
print(df_new_2)

                                       weighted_avg  difference_days_avg
vendor_name
A G AROMATICS PVT LTD                     66.256732            56.028571
A G Industries                           114.156045           115.166667
A Von Stationers & Packers                18.000000            18.000000
ABHAY                                     18.253904            18.500000
ALCHEM LABORATORIES                       40.000000            40.000000
ALPSPURE LIFESCIENCES PVT LTD             89.450803            84.666667
AMBE PHYTOEXTRACTS PVT LTD                 2.317095             8.500000
AMBE PHYTOEXTRACTS PVT LTD(PAURI)         12.454545            19.000000
ANIL KUMAR                                18.627026            17.000000
ANKUR HERBAL PRODUCTS                    161.000000           161.000000
ARUN ENTERPRISES                           4.919023             5.000000
AUSHADHI PHYTOEXTRACTS                   -21.000000           -21.000000
AVS ENTERPRISES                           50.255132            62.000000
Akansha Maheshwari                        53.000000            53.000000
Arbro Pharmaceuticals private limited     16.260331            16.333333
BHOODEEP                                  18.491371            18.500000
DELHI MODI  EXPRESS TRANSPORT COMPANY     24.844628            16.500000
DIVESH                                    17.000000            17.000000
EXPO ESSENTIAL OILS                        5.000000             5.000000
G.S. PLASTIC INDUSTRIES                   18.000000            18.000000
GANPATI BIOTECH                           55.950752            59.666667
GARIMA                                    18.500000            18.500000
GLOBAL AROMATICS                          25.000000            25.000000
GLOW PACKAGING PRIVATE LIMITED             1.452004             6.200000
Guru Kripa Marketing                      57.358578            51.500000
HARI OIL MILLS & COMPANY                   4.000000             4.000000
HERBAVEDA OVERSEAS                        34.536029            23.080000
HERBOTREE                                  6.000000             6.000000
JANKI JI MANGAL UDYOG                     -1.115442            -1.000000
JDMT ENGINEERING INDIA PVT LTD            94.000000            94.000000
...                                             ...                  ...
PUSHAPRAJ                                 16.000000            16.000000
QUAD LIFESCIENCES PVT LTD                 15.000000            15.000000
R P GUPTA & SONS                          61.226653            19.571429
RADHEY SHYAM SHARAD KUMAR                 50.026968            38.800000
RAJKUMAR                                  16.830746            17.500000
RATISH                                    17.500000            17.500000
RAYITAK FLAVOUR & FRAGRANCE               55.939960            53.500000
RUDRAKSH CHEMICALS                        40.016083            25.285714
Rakesh Scientific Centre                  41.000000            41.000000
S R IMPEX                                  3.298992            -0.250000
SATYAM ENTERPRISES                         2.000000             2.000000
SHARDA CONTAINERS PVT LTD                 53.000000            53.000000
SHIVAM SALES                              13.000000            13.000000
SHREE JI CHEMICAL CO                       1.000000             1.000000
SHREE RADHEY ENTERPRISES                   5.176469             5.500000
SHREEDHA PHYTO EXTRACT                    40.064980            48.714286
SHUDHANTA HERBAL PRODUCTS                 14.000000            14.000000
SONIKA                                     1.263158             2.000000
SOVAM CROP SCIENCE PVT LTD                40.000000            40.000000
SURAJ                                     32.000000            32.000000
SURAJBALA EXPORTS (P) LTD                153.263649           147.777778
SYSTEM SOLUTIONS                          22.000000            22.000000
THE BANGALORE SALES CORPORATION           16.608005            16.000000
THE INDIA CHEMICAL CO                     32.068389            37.857143
THUKRAL TRADING CO.                       13.000000            13.000000
U & I                                    -26.000000           -26.000000
VDH ORGANICS PVT LTD                      22.458378            19.500000
VIVAAN HERBAL AND HEALTHCARE              94.683968            78.727273
WRG Steel industries pvt ltd              19.666667            19.666667
Zoho Technologies Private Limited         -1.000000            -1.000000

[74 rows x 2 columns]

In [21]:
df_bill_2 = pd.DataFrame(columns=['vendor_name','balance','age'])
for i in range(len(df_bill_sheet)):
    #print(str(df_invoices.iloc[i][['due_days']]).split(" ")[4])
    vendor_name = df_bill_sheet.iloc[i]['vendor_name'] 
    balance = df_bill_sheet.iloc[i]['balance']
    #print(balance,customer_name)
    age=" "
    
    if(df_bill_sheet.iloc[i]['due_days'].split(" ")[0]=='Overdue'):
        #print(int(str(df_invoices.iloc[i][['due_days']]).split(" ")[6]) * 1)
        age = int(df_bill_sheet.iloc[i]['due_days'].split(" ")[2]) * 1
    elif(df_bill_sheet.iloc[i]['due_days'].split(" ")[0]=='Due'):
        #print(int(str(df_invoices.iloc[i][['due_days']]).split(" ")[6]) * -1)
        if(df_bill_sheet.iloc[i]['due_days'].split(" ")[1]=='Today'):
            age=0
        else:
            age = int(df_bill_sheet.iloc[i]['due_days'].split(" ")[2]) * -1
    
    df_bill_2 = df_bill_2.append({
        'vendor_name':vendor_name,
        'balance':balance,
        'age':age,
    },ignore_index=True)

In [ ]:
df_wk1 = df_wk2 = df_wk3 = df_wk4 = pd.DataFrame()
four_wk_report = [df_wk1,df_wk2,df_wk3,df_wk4]
for i in range(len(four_wk_report)):
    df_temp = pd.DataFrame()
    for k in range(len(df_bill_2)):
        vendor_name = df_bill_2.iloc[k]['vendor_name']
        balance = df_bill_2.iloc[k]['balance']
        if(df_bill_2.iloc[k]['age'] != ' '):
            new_age = int(df_bill_2.iloc[k]['age']) + (i*7)
            weighted_avg=difference_days_avg = "No record"
            if(new_age >= 0):
                for j in range(len(df_new_2)):
                    weighted_avg_list = list(df_new_2.weighted_avg[df_new_2.index == vendor_name])
                    difference_days_avg_list = list(df_new_2.difference_days_avg[df_new_2.index == vendor_name])

                    if(weighted_avg_list):
                        weighted_avg = weighted_avg_list[0]
                    if(difference_days_avg_list):
                        difference_days_avg = difference_days_avg_list[0]

                        
                        
                df_temp = df_temp.append({
                    'Vendor Name': vendor_name,
                    'Balance': balance,
                    'Age' : new_age,
                    'A_Weighted average':weighted_avg,
                    'A_Difference days average':difference_days_avg,
                },ignore_index=True)
    four_wk_report[i] = df_temp